'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict');
const cp=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {createStore}=require('../lib/store'),{passwordHash,sha,totp}=require('../lib/security');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'onebiz-test-')),file=path.join(dir,'test.sqlite'),key='22'.repeat(32),origin='http://127.0.0.1:18887';let child,s;let a,b,admin,viewer;
class Client{
 constructor(){this.cookies={};this.csrf='';this.bearer='';}
 async request(p,method='GET',data,overrides={}){
  const headers={'Content-Type':'application/json','X-Onebiz-Client':this.bearer?'android':'web',Origin:origin,'X-CSRF-Token':this.csrf,Cookie:Object.entries(this.cookies).map(([k,v])=>k+'='+v).join('; '),...overrides};if(this.bearer)headers.Authorization='Bearer '+this.bearer;
  const r=await fetch(origin+p,{method,headers,redirect:'manual',...(data!==undefined?{body:JSON.stringify(data)}:{})});
  for(const c of r.headers.getSetCookie()){const [p]=c.split(';');const [k,...v]=p.split('=');this.cookies[k]=v.join('=');}
  const text=await r.text();let body;try{body=JSON.parse(text);}catch{body={text};}if(body.csrf)this.csrf=body.csrf;return {status:r.status,body,headers:r.headers};
 }
}
async function signup(number){const c=new Client(),r=await c.request('/api/auth/phone/request','POST',{phone:number,terms:true,privacy:true});assert.equal(r.status,200,JSON.stringify(r.body));const v=await c.request('/api/auth/phone/verify','POST',{challengeId:r.body.challengeId,code:r.body.demoCode});assert.equal(v.status,200,JSON.stringify(v.body));c.id=v.body.user.id;return c;}
async function profile(c,name){const r=await c.request('/api/profile','PUT',{revision:0,profile:{profileType:'PERSONAL',representative:name}});assert.equal(r.status,200);}
before(async()=>{
 s=createStore(file,key);for(const [name,role]of [['owner','owner'],['viewer','viewer']]){const salt='test-salt';s.run('INSERT INTO admins(id,username,salt,password,totp,role) VALUES(?,?,?,?,?,?)',name,name,salt,passwordHash('Test-Only-Password-2026',salt),null,role);}
 child=cp.spawn(process.execPath,['server.js'],{cwd:path.join(__dirname,'..'),env:{...process.env,APP_MODE:'test',PORT:'18887',PUBLIC_ORIGIN:origin,DATA_FILE:file,DATA_KEY_HEX:key,KAKAO_CLIENT_ID:'test-client',KAKAO_CLIENT_SECRET:'test-secret'},stdio:'pipe'});
 let ready=false;for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,100));try{if((await fetch(origin+'/health')).ok){ready=true;break;}}catch{}}
 assert.ok(ready,'server startup');
 a=await signup('01000000001');b=await signup('01000000002');await profile(a,'가상사용자A');await profile(b,'가상사용자B');
 admin=new Client();assert.equal((await admin.request('/api/admin/login','POST',{username:'owner',password:'Test-Only-Password-2026'})).status,200);
 viewer=new Client();assert.equal((await viewer.request('/api/admin/login','POST',{username:'viewer',password:'Test-Only-Password-2026'})).status,200);
});
after(()=>{child?.kill('SIGTERM');s?.db.close();});
const data=(name)=>({customers:[{name,phone:'01099999999'}],quotes:[],contracts:[]});
test('휴대폰 인증 후 프로필 분리 / 이름만으로 개인 등록',async()=>{const r=await a.request('/api/me');assert.equal(r.body.user.profileComplete,true);assert.equal(r.body.user.profile.profileType,'PERSONAL');assert.deepEqual(r.body.user.identities,['phone']);});
test('필수동의 누락과 잘못된 전화번호 거부',async()=>{const c=new Client();assert.equal((await c.request('/api/auth/phone/request','POST',{phone:'01000000003'})).status,400);assert.equal((await c.request('/api/auth/phone/request','POST',{phone:'123',terms:true,privacy:true})).status,400);});
test('OTP 오입력·재사용·연속발송 거부',async()=>{const c=new Client(),r=await c.request('/api/auth/phone/request','POST',{phone:'01000000004',terms:true,privacy:true});assert.equal(r.status,200);const id=r.body.challengeId,code=r.body.demoCode;assert.equal((await c.request('/api/auth/phone/verify','POST',{challengeId:id,code:'not-code'})).status,400);assert.equal((await c.request('/api/auth/phone/verify','POST',{challengeId:id,code})).status,200);assert.equal((await c.request('/api/auth/phone/verify','POST',{challengeId:id,code})).status,400);assert.equal((await c.request('/api/auth/phone/request','POST',{phone:'01000000004',terms:true,privacy:true})).status,429);});
test('OTP 만료·5회 초과 차단',async()=>{const c=new Client(),r=await c.request('/api/auth/phone/request','POST',{phone:'01000000005',terms:true,privacy:true});s.run('UPDATE otp SET expires=? WHERE id=?',Date.now()-1,r.body.challengeId);assert.equal((await c.request('/api/auth/phone/verify','POST',{challengeId:r.body.challengeId,code:r.body.demoCode})).status,400);const r2=await c.request('/api/auth/phone/request','POST',{phone:'01000000006',terms:true,privacy:true});for(let i=0;i<5;i++)assert.equal((await c.request('/api/auth/phone/verify','POST',{challengeId:r2.body.challengeId,code:'WRONG'})).status,400);assert.equal((await c.request('/api/auth/phone/verify','POST',{challengeId:r2.body.challengeId,code:r2.body.demoCode})).status,400);});
test('비로그인 데이터 접근·일반회원 관리자 접근 차단',async()=>{assert.equal((await(new Client()).request('/api/snapshot')).status,401);assert.equal((await a.request('/api/admin/users')).status,401);});
test('CSRF / 외부 Origin 쓰기 차단',async()=>{assert.equal((await a.request('/api/profile','PUT',{revision:1,profile:{representative:'X'}},{'X-CSRF-Token':'bad'})).status,403);assert.equal((await a.request('/api/profile','PUT',{revision:1,profile:{representative:'X'}},{Origin:'https://evil.example'})).status,403);});
test('서버가 사용자 ID를 결정 / 타 사용자 ID 주입 무시',async()=>{const r=await a.request('/api/snapshot','PUT',{revision:0,userId:b.id,data:data('A의 비공개 고객'),employees:[]});assert.equal(r.status,200);const got=await a.request('/api/snapshot');assert.equal(got.body.userId,a.id);const other=await b.request('/api/snapshot');assert.equal(other.body.data.customers.length,0);});
test('동시에 수정한 이전 버전의 덮어쓰기 409 / 기존 데이터 보존',async()=>{assert.equal((await a.request('/api/snapshot','PUT',{revision:0,data:data('오래된 값'),employees:[]})).status,409);const r=await a.request('/api/snapshot');assert.equal(r.body.data.customers[0].name,'A의 비공개 고객');});
test('프로필 버전 충돌 409',async()=>{assert.equal((await a.request('/api/profile','PUT',{revision:0,profile:{representative:'덮어쓰기'}})).status,409);});
test('정적 PIN·전역 기기키 V1 API 제거',async()=>{assert.equal((await a.request('/api/v1/session','POST',{memberId:a.id,pin:'123456'})).status,404);assert.equal((await a.request('/api/v1/device/snapshot?memberId='+b.id)).status,404);});
test('OAuth state 누락/타 브라우저 콜백 차단',async()=>{const r=await a.request('/api/auth/social/kakao','POST',{terms:true,privacy:true});assert.equal(r.status,200);const state=new URL(r.body.url).searchParams.get('state');assert.equal((await(new Client()).request('/auth/callback/kakao?code=invalid&state='+state)).status,400);assert.equal((await a.request('/auth/callback/kakao?code=invalid&state=wrong')).status,400);});
test('이미 다른 계정에 등록된 전화번호를 강제로 연결하지 않음',async()=>{s.run('DELETE FROM rates WHERE k=?',s.hash('sms-minute:01000000002'));const r=await a.request('/api/auth/phone/request','POST',{phone:'01000000002',terms:true,privacy:true,link:true});assert.equal(r.status,200);const v=await a.request('/api/auth/phone/verify','POST',{challengeId:r.body.challengeId,code:r.body.demoCode});assert.equal(v.status,409);assert.equal((await a.request('/api/me')).body.user.id,a.id);});
test('Android 승인·검증자 일치·한 번만 교환·고유 계정 범위',async()=>{const c=new Client(),verifier=crypto.randomBytes(32).toString('base64url'),r=await c.request('/api/device/start','POST',{challenge:sha(verifier)});assert.equal(r.status,200);const id=r.body.requestId;assert.equal((await c.request('/api/device/poll','POST',{requestId:id,verifier})).status,202);assert.equal((await c.request('/api/device/poll','POST',{requestId:id,verifier:'A'.repeat(43)})).status,400);assert.equal((await a.request('/api/device/approve','POST',{requestId:id,confirm:true})).status,200);const signed=await c.request('/api/device/poll','POST',{requestId:id,verifier});assert.equal(signed.status,200);assert.equal(signed.body.userId,a.id);c.bearer=signed.body.token;assert.equal((await c.request('/api/snapshot')).body.userId,a.id);assert.equal((await c.request('/api/device/poll','POST',{requestId:id,verifier})).status,400);});
test('웹 클라이언트의 임의 서명완료 생성 거부',async()=>{const payload=data('고객');payload.contracts=[{id:'C-FORGED',signed:true,amount:100}];assert.equal((await b.request('/api/snapshot','PUT',{revision:0,data:payload,employees:[]})).status,400);});
test('관리자 목록은 문서·고객명단·급여 미포함 / 마스킹',async()=>{const r=await admin.request('/api/admin/users');assert.equal(r.status,200);const str=JSON.stringify(r.body);assert.ok(!str.includes('A의 비공개 고객'));assert.ok(!str.includes('가상사용자A'));assert.ok(!str.includes('01099999999'));assert.ok(r.body.items.find(x=>x.id===a.id).counts.customers===1);assert.equal((await admin.request('/api/admin/users/'+a.id+'/snapshot')).status,404);});
test('조회전용 관리자는 공지·이용정지 권한 없음',async()=>{assert.equal((await viewer.request('/api/admin/notices','POST',{})).status,403);assert.equal((await viewer.request('/api/admin/users/'+a.id+'/status','PUT',{status:'suspended',reason:'권한 검증 테스트'})).status,403);assert.equal((await viewer.request('/api/admin/audit')).status,403);});
test('배차 등록 → 관리자 상세조회 기록 → 상태전환·충돌',async()=>{const r=await a.request('/api/dispatch','POST',{equipment:'사다리차',address:'예시시 예시구 비공개현장 101',date:'2026-09-21',floor:'3',goods:'자재',phone:'01000000001',minutes:30});assert.equal(r.status,201);const id=r.body.id;const list=await admin.request('/api/admin/dispatch');assert.ok(!JSON.stringify(list.body).includes('비공개현장'));assert.equal((await viewer.request('/api/admin/dispatch/'+id,'POST',{reason:'배차 운영 확인'})).status,403);assert.equal((await admin.request('/api/admin/dispatch/'+id,'POST',{reason:'배차 운영 확인'})).body.address,'예시시 예시구 비공개현장 101');assert.equal((await admin.request('/api/admin/dispatch/'+id,'PUT',{status:'작업완료',revision:1})).status,400);assert.equal((await admin.request('/api/admin/dispatch/'+id,'PUT',{status:'확인중',revision:1})).status,200);assert.equal((await admin.request('/api/admin/dispatch/'+id,'PUT',{status:'배차완료',revision:1})).status,409);});
test('특정 사용자 공지·게시기간 필터',async()=>{const now=Date.now();await admin.request('/api/admin/notices','POST',{title:'A전용',body:'별도 안내',target:a.id,starts:now-1000,ends:now+100000});await admin.request('/api/admin/notices','POST',{title:'예약공지',body:'예정',target:'all',starts:now+100000,ends:now+200000});assert.ok((await a.request('/api/notices')).body.items.some(n=>n.title==='A전용'));assert.ok(!(await b.request('/api/notices')).body.items.some(n=>n.title==='A전용'));assert.ok(!(await a.request('/api/notices')).body.items.some(n=>n.title==='예약공지'));});
test('DB 원문 암호화 / 손상 데이터 자동초기화하지 않음',()=>{const raw=s.one('SELECT body FROM snapshots WHERE user_id=?',a.id).body;assert.ok(!raw.includes('A의 비공개 고객'));assert.equal(s.open(raw).data.customers[0].name,'A의 비공개 고객');assert.throws(()=>s.open(raw+'corrupted'));});
test('감사로그는 인증번호·비밀번호·고객 원문을 포함하지 않음',async()=>{const r=await admin.request('/api/admin/audit');const raw=JSON.stringify(r.body);assert.ok(raw.includes('dispatch.detail'));assert.ok(!raw.includes('Test-Only-Password'));assert.ok(!raw.includes('A의 비공개 고객'));});
test('보안 헤더와 사용자/관리자 쿠키 분리',async()=>{const r=await a.request('/api/me');assert.equal(r.headers.get('x-frame-options'),'DENY');assert.ok(a.cookies.ob_user);assert.ok(admin.cookies.ob_admin);assert.equal((await a.request('/api/admin/me')).status,401);});
test('이용정지 시 사용자 세션 취소 / 관리자 요청 사유 필수',async()=>{assert.equal((await admin.request('/api/admin/users/'+b.id+'/status','PUT',{status:'suspended',reason:'x'})).status,400);assert.equal((await admin.request('/api/admin/users/'+b.id+'/status','PUT',{status:'suspended',reason:'보안 테스트로 임시 중지'})).status,200);assert.equal((await b.request('/api/me')).status,401);});
test('로그아웃된 세션 재사용 차단',async()=>{const old={...a.cookies};assert.equal((await a.request('/api/logout','POST')).status,200);a.cookies=old;assert.equal((await a.request('/api/me')).status,401);});
test('TOTP RFC6238 SHA1 8자리 벡터의 6자리 끝 값',()=>{assert.equal(totp('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ',1),'287082');});
test('production은 HTTPS·약관승인·암호화키 없으면 시작 거부',()=>{const r=cp.spawnSync(process.execPath,['server.js'],{cwd:path.join(__dirname,'..'),env:{...process.env,APP_MODE:'production',PUBLIC_ORIGIN:'http://localhost:19999',PORT:'19999',DATA_FILE:path.join(dir,'reject.sqlite')},timeout:5000});assert.notEqual(r.status,0);assert.ok(!fs.existsSync(path.join(dir,'reject.sqlite')));});
test('관리자 TOTP 미입력 거부 / 정상 코드 승인 / 재사용 거부',async()=>{const secret='GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ';s.run('UPDATE admins SET totp=?,last_step=-1 WHERE id=?',s.seal(secret),'viewer');const c=new Client(),payload={username:'viewer',password:'Test-Only-Password-2026'};assert.equal((await c.request('/api/admin/login','POST',payload)).status,401);payload.code=totp(secret);assert.equal((await c.request('/api/admin/login','POST',payload)).status,200);assert.equal((await c.request('/api/admin/login','POST',payload)).status,401);});
test('서버 소스·환경변수·DB 파일은 정적 경로로 노출되지 않음',async()=>{const c=new Client();for(const file of ['/server.js','/.env','/lib/store.js','/data/test.sqlite'])assert.equal((await c.request(file)).status,404);});
